version: 0.2

env:
  secrets-manager:
    TOKEN: firstSecret:tokenForSonar
    SNYK_TOKEN: secondSecret:tokenForSnyk

phases:
  install:
    runtime-versions:
      java: latest
    commands:
      # Grant execute permissions to the Gradle wrapper script
      - chmod +x ./gradlew
      
      # Install necessary packages for OWASP ZAP
      - apt-get update
      - apt-get -y install wget default-jdk

  build:
    commands:
      # Static Application Security Test (SAST) using SonarCloud
      - ./gradlew build -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=devsecopsapplication -Dsonar.projectKey=devsecopsapplication -Dsonar.login=$TOKEN sonar

      # Software Composition Analysis (SCA) using Snyk
      - export $SNYK_TOKEN
      - ./gradlew snyk-test

      # Dynamic Application Security Scan (DAST) using OWASP ZAP
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2.15.0_Linux.tar.gz
      - tar -xvf ZAP_2.15.0_Linux.tar.gz
      - cd ZAP_2.15.0
      - ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html

artifacts:
  files:
    - zap_report.html
